version: '3.1'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LOG_LEVEL=DEBUG
  kafka:
    depends_on:
      - zookeeper
    image: 'bitnami/kafka:latest'
    expose:
      - '9092'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  mysql:
    image: 'mysql:8'
    expose:
      - '3306'
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reengagement
      - MYSQL_USER=reengagement_user
      - MYSQL_PASSWORD=password
      - ALLOW_PUBLIC_KEY_RETRIEVAL=true
    command: ["--character-set-server=utf8", "--collation-server=utf8_general_ci"]

  postgres:
    image: 'postgres:12'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=lesson
      - POSTGRES_USER=lesson_user
      - POSTGRES_PASSWORD=password
      - ALLOW_PUBLIC_KEY_RETRIEVAL=true
